[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"
  functions = "netlify/functions"

[context.production]
  environment = { SECRETS_SCAN_OMIT_KEYS = "VITE_CLOUDINARY_UPLOAD_PRESET" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd client && npm run dev -- --host 127.0.0.1"
  targetPort = 5173
  framework = "vite"
